version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  reviewers:
  - nsidnev
  ignore:
  - dependency-name: edgedb
    versions:
    - 0.12.0
  - dependency-name: mkdocs-material
    versions:
    - 6.2.3
    - 6.2.7
  - dependency-name: pytest
    versions:
    - 6.2.1
