#!/usr/bin/env bash

set -e

# Sort imports one per line, so autoflake can remove unused imports
isort --recursive  --force-single-line-imports edgeql_queries tests example docs/src scripts

autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place edgeql_queries tests example docs/src scripts
black edgeql_queries tests example docs/src scripts
isort --recursive edgeql_queries tests scripts

# sort edgeql_queries imports as it third-party library
isort --recursive --thirdparty=edgeql_queries example docs/src
