#!/usr/bin/env bash

set -e
set -x


mypy edgeql_queries example
flake8 edgeql_queries

black --check edgeql_queries tests example docs/src
isort --recursive --check-only edgeql_queries tests

# check edgeql_queries imports are sorted as it third-party library
isort --recursive --check-only --thirdparty=edgeql_queries example docs/src
