name: Styles

on: push

jobs:
  styles:
    name: Styles

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9

      - name: Install Poetry
        run: |
          pip install poetry==1.1.8
          poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-py-${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv

      - name: Install dependencies
        run: |
          poetry install

      - name: Run linters
        run: |
          poetry run nox -s lint
