name: Tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        edgedb-version: [1-alpha5]
    services:
      edgedb:
        image: edgedb/edgedb:${{ matrix.edgedb-version }}
        ports:
          - 5656:5656
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry==1.0
          poetry config virtualenvs.in-project true
          poetry install
      - name: Install EdgeDB CLI
        run: |
          mkdir -p ~/.local/bin/
          curl https://packages.edgedb.com/dist/linux-x86_64/edgedb-cli_latest > ~/.local/bin/edgedb
          chmod +x ~/.local/bin/edgedb
      - name: Run tests
        env:
          EDGEDB_DSN: edgedb://edgedb@localhost/edgedb
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run nox -s test
      - uses: codecov/codecov-action@v1.0.6
